/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.story.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Story implements java.io.Serializable {

	private static final long serialVersionUID = 254578871;

	private java.lang.String   id;
	private java.lang.String   plot;
	private java.lang.String   writer;
	private java.lang.Long     upvotes;
	private java.lang.String   createdby;
	private java.lang.String   updatedby;
	private java.sql.Timestamp createddate;
	private java.sql.Timestamp updateddate;

	public Story() {}

	public Story(
		java.lang.String   id,
		java.lang.String   plot,
		java.lang.String   writer,
		java.lang.Long     upvotes,
		java.lang.String   createdby,
		java.lang.String   updatedby,
		java.sql.Timestamp createddate,
		java.sql.Timestamp updateddate
	) {
		this.id = id;
		this.plot = plot;
		this.writer = writer;
		this.upvotes = upvotes;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getPlot() {
		return this.plot;
	}

	public void setPlot(java.lang.String plot) {
		this.plot = plot;
	}

	public java.lang.String getWriter() {
		return this.writer;
	}

	public void setWriter(java.lang.String writer) {
		this.writer = writer;
	}

	public java.lang.Long getUpvotes() {
		return this.upvotes;
	}

	public void setUpvotes(java.lang.Long upvotes) {
		this.upvotes = upvotes;
	}

	public java.lang.String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(java.lang.String createdby) {
		this.createdby = createdby;
	}

	public java.lang.String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(java.lang.String updatedby) {
		this.updatedby = updatedby;
	}

	public java.sql.Timestamp getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(java.sql.Timestamp createddate) {
		this.createddate = createddate;
	}

	public java.sql.Timestamp getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(java.sql.Timestamp updateddate) {
		this.updateddate = updateddate;
	}
}
