/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysFunctionoperation;
import com.nanhu.model.sys.tables.records.SysFunctionoperationRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 功能操作表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysFunctionoperationDao extends DAOImpl<SysFunctionoperationRecord, com.nanhu.model.sys.tables.pojos.SysFunctionoperation, String> {

    /**
     * Create a new SysFunctionoperationDao without any configuration
     */
    public SysFunctionoperationDao() {
        super(SysFunctionoperation.SYS_FUNCTIONOPERATION, com.nanhu.model.sys.tables.pojos.SysFunctionoperation.class);
    }

    /**
     * Create a new SysFunctionoperationDao with an attached configuration
     */
    @Autowired
    public SysFunctionoperationDao(Configuration configuration) {
        super(SysFunctionoperation.SYS_FUNCTIONOPERATION, com.nanhu.model.sys.tables.pojos.SysFunctionoperation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysFunctionoperation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchById(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysFunctionoperation fetchOneById(String value) {
        return fetchOne(SysFunctionoperation.SYS_FUNCTIONOPERATION.ID, value);
    }

    /**
     * Fetch records that have <code>moduleId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByModuleid(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.MODULEID, values);
    }

    /**
     * Fetch records that have <code>funName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByFunname(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.FUNNAME, values);
    }

    /**
     * Fetch records that have <code>funParentId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByFunparentid(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.FUNPARENTID, values);
    }

    /**
     * Fetch records that have <code>funCode IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByFuncode(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.FUNCODE, values);
    }

    /**
     * Fetch records that have <code>interceptPrefix IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByInterceptprefix(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.INTERCEPTPREFIX, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByStatus(Byte... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.STATUS, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchBySort(Byte... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.SORT, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByCreator(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByModifier(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByCreatedate(Timestamp... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>modifyDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByModifydate(Timestamp... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.MODIFYDATE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysFunctionoperation> fetchByRemark(String... values) {
        return fetch(SysFunctionoperation.SYS_FUNCTIONOPERATION.REMARK, values);
    }
}
