/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysGroup;
import com.nanhu.model.sys.tables.records.SysGroupRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 组
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysGroupDao extends DAOImpl<SysGroupRecord, com.nanhu.model.sys.tables.pojos.SysGroup, String> {

    /**
     * Create a new SysGroupDao without any configuration
     */
    public SysGroupDao() {
        super(SysGroup.SYS_GROUP, com.nanhu.model.sys.tables.pojos.SysGroup.class);
    }

    /**
     * Create a new SysGroupDao with an attached configuration
     */
    @Autowired
    public SysGroupDao(Configuration configuration) {
        super(SysGroup.SYS_GROUP, com.nanhu.model.sys.tables.pojos.SysGroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysGroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchById(String... values) {
        return fetch(SysGroup.SYS_GROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysGroup fetchOneById(String value) {
        return fetchOne(SysGroup.SYS_GROUP.ID, value);
    }

    /**
     * Fetch records that have <code>groupName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByGroupname(String... values) {
        return fetch(SysGroup.SYS_GROUP.GROUPNAME, values);
    }

    /**
     * Fetch records that have <code>groupParentId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByGroupparentid(String... values) {
        return fetch(SysGroup.SYS_GROUP.GROUPPARENTID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByStatus(Byte... values) {
        return fetch(SysGroup.SYS_GROUP.STATUS, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchBySort(Byte... values) {
        return fetch(SysGroup.SYS_GROUP.SORT, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByCreator(String... values) {
        return fetch(SysGroup.SYS_GROUP.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByModifier(String... values) {
        return fetch(SysGroup.SYS_GROUP.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByCreatedate(Timestamp... values) {
        return fetch(SysGroup.SYS_GROUP.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>modifyDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByModifydate(Timestamp... values) {
        return fetch(SysGroup.SYS_GROUP.MODIFYDATE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysGroup> fetchByRemark(String... values) {
        return fetch(SysGroup.SYS_GROUP.REMARK, values);
    }
}
