/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysLoginUser;
import com.nanhu.model.sys.tables.records.SysLoginUserRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysLoginUserDao extends DAOImpl<SysLoginUserRecord, com.nanhu.model.sys.tables.pojos.SysLoginUser, String> {

    /**
     * Create a new SysLoginUserDao without any configuration
     */
    public SysLoginUserDao() {
        super(SysLoginUser.SYS_LOGIN_USER, com.nanhu.model.sys.tables.pojos.SysLoginUser.class);
    }

    /**
     * Create a new SysLoginUserDao with an attached configuration
     */
    @Autowired
    public SysLoginUserDao(Configuration configuration) {
        super(SysLoginUser.SYS_LOGIN_USER, com.nanhu.model.sys.tables.pojos.SysLoginUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysLoginUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchById(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysLoginUser fetchOneById(String value) {
        return fetchOne(SysLoginUser.SYS_LOGIN_USER.ID, value);
    }

    /**
     * Fetch records that have <code>groupId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByGroupid(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.GROUPID, values);
    }

    /**
     * Fetch records that have <code>loginName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByLoginname(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.LOGINNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByPassword(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>userName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByUsername(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>mobile IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByMobile(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.MOBILE, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByEmail(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchBySalt(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.SALT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByStatus(Byte... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchBySort(Byte... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.SORT, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByCreator(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByModifier(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByCreatedate(Timestamp... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>modifyDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByModifydate(Timestamp... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.MODIFYDATE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLoginUser> fetchByRemark(String... values) {
        return fetch(SysLoginUser.SYS_LOGIN_USER.REMARK, values);
    }
}
