/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysLog;
import com.nanhu.model.sys.tables.records.SysLogRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 操作日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysLogDao extends DAOImpl<SysLogRecord, com.nanhu.model.sys.tables.pojos.SysLog, String> {

    /**
     * Create a new SysLogDao without any configuration
     */
    public SysLogDao() {
        super(SysLog.SYS_LOG, com.nanhu.model.sys.tables.pojos.SysLog.class);
    }

    /**
     * Create a new SysLogDao with an attached configuration
     */
    @Autowired
    public SysLogDao(Configuration configuration) {
        super(SysLog.SYS_LOG, com.nanhu.model.sys.tables.pojos.SysLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLog> fetchById(String... values) {
        return fetch(SysLog.SYS_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysLog fetchOneById(String value) {
        return fetchOne(SysLog.SYS_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>operationName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLog> fetchByOperationname(String... values) {
        return fetch(SysLog.SYS_LOG.OPERATIONNAME, values);
    }

    /**
     * Fetch records that have <code>operationContent IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLog> fetchByOperationcontent(String... values) {
        return fetch(SysLog.SYS_LOG.OPERATIONCONTENT, values);
    }

    /**
     * Fetch records that have <code>operationUser IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLog> fetchByOperationuser(String... values) {
        return fetch(SysLog.SYS_LOG.OPERATIONUSER, values);
    }

    /**
     * Fetch records that have <code>operationDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysLog> fetchByOperationdate(Timestamp... values) {
        return fetch(SysLog.SYS_LOG.OPERATIONDATE, values);
    }
}
