/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysPosition;
import com.nanhu.model.sys.tables.records.SysPositionRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 职位
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysPositionDao extends DAOImpl<SysPositionRecord, com.nanhu.model.sys.tables.pojos.SysPosition, String> {

    /**
     * Create a new SysPositionDao without any configuration
     */
    public SysPositionDao() {
        super(SysPosition.SYS_POSITION, com.nanhu.model.sys.tables.pojos.SysPosition.class);
    }

    /**
     * Create a new SysPositionDao with an attached configuration
     */
    @Autowired
    public SysPositionDao(Configuration configuration) {
        super(SysPosition.SYS_POSITION, com.nanhu.model.sys.tables.pojos.SysPosition.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysPosition object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchById(String... values) {
        return fetch(SysPosition.SYS_POSITION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysPosition fetchOneById(String value) {
        return fetchOne(SysPosition.SYS_POSITION.ID, value);
    }

    /**
     * Fetch records that have <code>positionName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByPositionname(String... values) {
        return fetch(SysPosition.SYS_POSITION.POSITIONNAME, values);
    }

    /**
     * Fetch records that have <code>positionCode IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByPositioncode(String... values) {
        return fetch(SysPosition.SYS_POSITION.POSITIONCODE, values);
    }

    /**
     * Fetch records that have <code>positionParentId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByPositionparentid(String... values) {
        return fetch(SysPosition.SYS_POSITION.POSITIONPARENTID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByStatus(Byte... values) {
        return fetch(SysPosition.SYS_POSITION.STATUS, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchBySort(Byte... values) {
        return fetch(SysPosition.SYS_POSITION.SORT, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByCreator(String... values) {
        return fetch(SysPosition.SYS_POSITION.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByModifier(String... values) {
        return fetch(SysPosition.SYS_POSITION.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByCreatedate(Timestamp... values) {
        return fetch(SysPosition.SYS_POSITION.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>modifyDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByModifydate(Timestamp... values) {
        return fetch(SysPosition.SYS_POSITION.MODIFYDATE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysPosition> fetchByRemark(String... values) {
        return fetch(SysPosition.SYS_POSITION.REMARK, values);
    }
}
