/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysSubsystemModule;
import com.nanhu.model.sys.tables.records.SysSubsystemModuleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 子系统模块
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysSubsystemModuleDao extends DAOImpl<SysSubsystemModuleRecord, com.nanhu.model.sys.tables.pojos.SysSubsystemModule, String> {

    /**
     * Create a new SysSubsystemModuleDao without any configuration
     */
    public SysSubsystemModuleDao() {
        super(SysSubsystemModule.SYS_SUBSYSTEM_MODULE, com.nanhu.model.sys.tables.pojos.SysSubsystemModule.class);
    }

    /**
     * Create a new SysSubsystemModuleDao with an attached configuration
     */
    @Autowired
    public SysSubsystemModuleDao(Configuration configuration) {
        super(SysSubsystemModule.SYS_SUBSYSTEM_MODULE, com.nanhu.model.sys.tables.pojos.SysSubsystemModule.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysSubsystemModule object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchById(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysSubsystemModule fetchOneById(String value) {
        return fetchOne(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.ID, value);
    }

    /**
     * Fetch records that have <code>subSystemId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchBySubsystemid(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.SUBSYSTEMID, values);
    }

    /**
     * Fetch records that have <code>moduleName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByModulename(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.MODULENAME, values);
    }

    /**
     * Fetch records that have <code>moduleCode IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByModulecode(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.MODULECODE, values);
    }

    /**
     * Fetch records that have <code>moduleParentId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByModuleparentid(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.MODULEPARENTID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByStatus(Byte... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.STATUS, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchBySort(Byte... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.SORT, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByCreator(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByModifier(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByCreatedate(Timestamp... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>modifyDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByModifydate(Timestamp... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.MODIFYDATE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystemModule> fetchByRemark(String... values) {
        return fetch(SysSubsystemModule.SYS_SUBSYSTEM_MODULE.REMARK, values);
    }
}
