/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysSubsystem;
import com.nanhu.model.sys.tables.records.SysSubsystemRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 子系统
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysSubsystemDao extends DAOImpl<SysSubsystemRecord, com.nanhu.model.sys.tables.pojos.SysSubsystem, String> {

    /**
     * Create a new SysSubsystemDao without any configuration
     */
    public SysSubsystemDao() {
        super(SysSubsystem.SYS_SUBSYSTEM, com.nanhu.model.sys.tables.pojos.SysSubsystem.class);
    }

    /**
     * Create a new SysSubsystemDao with an attached configuration
     */
    @Autowired
    public SysSubsystemDao(Configuration configuration) {
        super(SysSubsystem.SYS_SUBSYSTEM, com.nanhu.model.sys.tables.pojos.SysSubsystem.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nanhu.model.sys.tables.pojos.SysSubsystem object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchById(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nanhu.model.sys.tables.pojos.SysSubsystem fetchOneById(String value) {
        return fetchOne(SysSubsystem.SYS_SUBSYSTEM.ID, value);
    }

    /**
     * Fetch records that have <code>subSystemName IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchBySubsystemname(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.SUBSYSTEMNAME, values);
    }

    /**
     * Fetch records that have <code>systemUrl IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchBySystemurl(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.SYSTEMURL, values);
    }

    /**
     * Fetch records that have <code>subSystemCode IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchBySubsystemcode(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.SUBSYSTEMCODE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchByStatus(Byte... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.STATUS, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchBySort(Byte... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.SORT, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchByCreator(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.CREATOR, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchByModifier(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>createDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchByCreatedate(Timestamp... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>modifyDate IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchByModifydate(Timestamp... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.MODIFYDATE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysSubsystem> fetchByRemark(String... values) {
        return fetch(SysSubsystem.SYS_SUBSYSTEM.REMARK, values);
    }
}
