/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.daos;


import com.nanhu.model.sys.tables.SysUsergroupRole;
import com.nanhu.model.sys.tables.records.SysUsergroupRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 用户组与角色关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysUsergroupRoleDao extends DAOImpl<SysUsergroupRoleRecord, com.nanhu.model.sys.tables.pojos.SysUsergroupRole, Record2<String, String>> {

    /**
     * Create a new SysUsergroupRoleDao without any configuration
     */
    public SysUsergroupRoleDao() {
        super(SysUsergroupRole.SYS_USERGROUP_ROLE, com.nanhu.model.sys.tables.pojos.SysUsergroupRole.class);
    }

    /**
     * Create a new SysUsergroupRoleDao with an attached configuration
     */
    @Autowired
    public SysUsergroupRoleDao(Configuration configuration) {
        super(SysUsergroupRole.SYS_USERGROUP_ROLE, com.nanhu.model.sys.tables.pojos.SysUsergroupRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.nanhu.model.sys.tables.pojos.SysUsergroupRole object) {
        return compositeKeyRecord(object.getRoleid(), object.getGroupid());
    }

    /**
     * Fetch records that have <code>roleId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysUsergroupRole> fetchByRoleid(String... values) {
        return fetch(SysUsergroupRole.SYS_USERGROUP_ROLE.ROLEID, values);
    }

    /**
     * Fetch records that have <code>roleCode IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysUsergroupRole> fetchByRolecode(String... values) {
        return fetch(SysUsergroupRole.SYS_USERGROUP_ROLE.ROLECODE, values);
    }

    /**
     * Fetch records that have <code>groupId IN (values)</code>
     */
    public List<com.nanhu.model.sys.tables.pojos.SysUsergroupRole> fetchByGroupid(String... values) {
        return fetch(SysUsergroupRole.SYS_USERGROUP_ROLE.GROUPID, values);
    }
}
