/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.story;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in spring_boot
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table spring_boot.story
	 */
	public static final com.nanhu.model.story.tables.Story STORY = com.nanhu.model.story.tables.Story.STORY;
}
