/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables;


import com.nanhu.model.sys.SpringBoot;
import com.nanhu.model.sys.tables.records.SysMenuRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu extends TableImpl<SysMenuRecord> {

    private static final long serialVersionUID = -1836737111;

    /**
     * The reference instance of <code>spring_boot.sys_menu</code>
     */
    public static final SysMenu SYS_MENU = new SysMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysMenuRecord> getRecordType() {
        return SysMenuRecord.class;
    }

    /**
     * The column <code>spring_boot.sys_menu.id</code>. 菜单ID
     */
    public final TableField<SysMenuRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "菜单ID");

    /**
     * The column <code>spring_boot.sys_menu.moduleId</code>. 子系统模块ID
     */
    public final TableField<SysMenuRecord, String> MODULEID = createField("moduleId", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "子系统模块ID");

    /**
     * The column <code>spring_boot.sys_menu.menuName</code>. 菜单名称
     */
    public final TableField<SysMenuRecord, String> MENUNAME = createField("menuName", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "菜单名称");

    /**
     * The column <code>spring_boot.sys_menu.menuParentId</code>. 菜单父节点
     */
    public final TableField<SysMenuRecord, String> MENUPARENTID = createField("menuParentId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "菜单父节点");

    /**
     * The column <code>spring_boot.sys_menu.menuCode</code>. 菜单编码（MENU_ 开头）
     */
    public final TableField<SysMenuRecord, String> MENUCODE = createField("menuCode", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "菜单编码（MENU_ 开头）");

    /**
     * The column <code>spring_boot.sys_menu.level</code>. 级别（最多四级）
     */
    public final TableField<SysMenuRecord, Byte> LEVEL = createField("level", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "级别（最多四级）");

    /**
     * The column <code>spring_boot.sys_menu.menuHref</code>. 访问路径
     */
    public final TableField<SysMenuRecord, String> MENUHREF = createField("menuHref", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "访问路径");

    /**
     * The column <code>spring_boot.sys_menu.menuIcon</code>. 图标（关联图片文件管理表获取）
     */
    public final TableField<SysMenuRecord, String> MENUICON = createField("menuIcon", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "图标（关联图片文件管理表获取）");

    /**
     * The column <code>spring_boot.sys_menu.status</code>. 状态(99：删除,10：启用 ,20：禁用)
     */
    public final TableField<SysMenuRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "状态(99：删除,10：启用 ,20：禁用)");

    /**
     * The column <code>spring_boot.sys_menu.sort</code>. 排序
     */
    public final TableField<SysMenuRecord, Byte> SORT = createField("sort", org.jooq.impl.SQLDataType.TINYINT, this, "排序");

    /**
     * The column <code>spring_boot.sys_menu.creator</code>. 创建用户Id
     */
    public final TableField<SysMenuRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "创建用户Id");

    /**
     * The column <code>spring_boot.sys_menu.modifier</code>. 修改用户Id
     */
    public final TableField<SysMenuRecord, String> MODIFIER = createField("modifier", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "修改用户Id");

    /**
     * The column <code>spring_boot.sys_menu.createDate</code>. 创建时间
     */
    public final TableField<SysMenuRecord, Timestamp> CREATEDATE = createField("createDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>spring_boot.sys_menu.modifyDate</code>. 修改时间
     */
    public final TableField<SysMenuRecord, Timestamp> MODIFYDATE = createField("modifyDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>spring_boot.sys_menu.remark</code>. 备注
     */
    public final TableField<SysMenuRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "备注");

    /**
     * Create a <code>spring_boot.sys_menu</code> table reference
     */
    public SysMenu() {
        this("sys_menu", null);
    }

    /**
     * Create an aliased <code>spring_boot.sys_menu</code> table reference
     */
    public SysMenu(String alias) {
        this(alias, SYS_MENU);
    }

    private SysMenu(String alias, Table<SysMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysMenu(String alias, Table<SysMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpringBoot.SPRING_BOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenu as(String alias) {
        return new SysMenu(alias, this);
    }

    /**
     * Rename this table
     */
    public SysMenu rename(String name) {
        return new SysMenu(name, null);
    }
}
