/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables;


import com.nanhu.model.sys.Keys;
import com.nanhu.model.sys.SpringBoot;
import com.nanhu.model.sys.tables.records.SysOrgPositionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 组织与职位
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrgPosition extends TableImpl<SysOrgPositionRecord> {

    private static final long serialVersionUID = 631617232;

    /**
     * The reference instance of <code>spring_boot.sys_org_position</code>
     */
    public static final SysOrgPosition SYS_ORG_POSITION = new SysOrgPosition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysOrgPositionRecord> getRecordType() {
        return SysOrgPositionRecord.class;
    }

    /**
     * The column <code>spring_boot.sys_org_position.orgId</code>.
     */
    public final TableField<SysOrgPositionRecord, String> ORGID = createField("orgId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.positionId</code>.
     */
    public final TableField<SysOrgPositionRecord, String> POSITIONID = createField("positionId", org.jooq.impl.SQLDataType.CHAR.length(10).nullable(false), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.status</code>.
     */
    public final TableField<SysOrgPositionRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.sort</code>.
     */
    public final TableField<SysOrgPositionRecord, Byte> SORT = createField("sort", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>spring_boot.sys_org_position.creator</code>.
     */
    public final TableField<SysOrgPositionRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.modifier</code>.
     */
    public final TableField<SysOrgPositionRecord, String> MODIFIER = createField("modifier", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.createDate</code>.
     */
    public final TableField<SysOrgPositionRecord, Timestamp> CREATEDATE = createField("createDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.modifyDate</code>.
     */
    public final TableField<SysOrgPositionRecord, Timestamp> MODIFYDATE = createField("modifyDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>spring_boot.sys_org_position.remark</code>.
     */
    public final TableField<SysOrgPositionRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>spring_boot.sys_org_position</code> table reference
     */
    public SysOrgPosition() {
        this("sys_org_position", null);
    }

    /**
     * Create an aliased <code>spring_boot.sys_org_position</code> table reference
     */
    public SysOrgPosition(String alias) {
        this(alias, SYS_ORG_POSITION);
    }

    private SysOrgPosition(String alias, Table<SysOrgPositionRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysOrgPosition(String alias, Table<SysOrgPositionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "组织与职位");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpringBoot.SPRING_BOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysOrgPositionRecord> getPrimaryKey() {
        return Keys.KEY_SYS_ORG_POSITION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysOrgPositionRecord>> getKeys() {
        return Arrays.<UniqueKey<SysOrgPositionRecord>>asList(Keys.KEY_SYS_ORG_POSITION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPosition as(String alias) {
        return new SysOrgPosition(alias, this);
    }

    /**
     * Rename this table
     */
    public SysOrgPosition rename(String name) {
        return new SysOrgPosition(name, null);
    }
}
