/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables;


import com.nanhu.model.sys.SpringBoot;
import com.nanhu.model.sys.tables.records.SysPermissionUserRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * 权限用户关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionUser extends TableImpl<SysPermissionUserRecord> {

    private static final long serialVersionUID = 845608631;

    /**
     * The reference instance of <code>spring_boot.sys_permission_user</code>
     */
    public static final SysPermissionUser SYS_PERMISSION_USER = new SysPermissionUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysPermissionUserRecord> getRecordType() {
        return SysPermissionUserRecord.class;
    }

    /**
     * The column <code>spring_boot.sys_permission_user.userId</code>. 用户ID
     */
    public final TableField<SysPermissionUserRecord, String> USERID = createField("userId", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "用户ID");

    /**
     * The column <code>spring_boot.sys_permission_user.resourcesId</code>. 资源ID
     */
    public final TableField<SysPermissionUserRecord, String> RESOURCESID = createField("resourcesId", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "资源ID");

    /**
     * Create a <code>spring_boot.sys_permission_user</code> table reference
     */
    public SysPermissionUser() {
        this("sys_permission_user", null);
    }

    /**
     * Create an aliased <code>spring_boot.sys_permission_user</code> table reference
     */
    public SysPermissionUser(String alias) {
        this(alias, SYS_PERMISSION_USER);
    }

    private SysPermissionUser(String alias, Table<SysPermissionUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysPermissionUser(String alias, Table<SysPermissionUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "权限用户关联表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpringBoot.SPRING_BOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionUser as(String alias) {
        return new SysPermissionUser(alias, this);
    }

    /**
     * Rename this table
     */
    public SysPermissionUser rename(String name) {
        return new SysPermissionUser(name, null);
    }
}
