/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables;


import com.nanhu.model.sys.SpringBoot;
import com.nanhu.model.sys.tables.records.SysPermissionGroupRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * 组权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionGroup extends TableImpl<SysPermissionGroupRecord> {

    private static final long serialVersionUID = -104287011;

    /**
     * The reference instance of <code>spring_boot.sys_permission_group</code>
     */
    public static final SysPermissionGroup SYS_PERMISSION_GROUP = new SysPermissionGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysPermissionGroupRecord> getRecordType() {
        return SysPermissionGroupRecord.class;
    }

    /**
     * The column <code>spring_boot.sys_permission_group.groupId</code>. 组ID
     */
    public final TableField<SysPermissionGroupRecord, String> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "组ID");

    /**
     * The column <code>spring_boot.sys_permission_group.resourcesId</code>. 资源ID
     */
    public final TableField<SysPermissionGroupRecord, String> RESOURCESID = createField("resourcesId", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "资源ID");

    /**
     * Create a <code>spring_boot.sys_permission_group</code> table reference
     */
    public SysPermissionGroup() {
        this("sys_permission_group", null);
    }

    /**
     * Create an aliased <code>spring_boot.sys_permission_group</code> table reference
     */
    public SysPermissionGroup(String alias) {
        this(alias, SYS_PERMISSION_GROUP);
    }

    private SysPermissionGroup(String alias, Table<SysPermissionGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysPermissionGroup(String alias, Table<SysPermissionGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "组权限表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpringBoot.SPRING_BOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionGroup as(String alias) {
        return new SysPermissionGroup(alias, this);
    }

    /**
     * Rename this table
     */
    public SysPermissionGroup rename(String name) {
        return new SysPermissionGroup(name, null);
    }
}
