/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables;


import com.nanhu.model.sys.Keys;
import com.nanhu.model.sys.SpringBoot;
import com.nanhu.model.sys.tables.records.SysUsergroupRoleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户组与角色关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUsergroupRole extends TableImpl<SysUsergroupRoleRecord> {

    private static final long serialVersionUID = 272875392;

    /**
     * The reference instance of <code>spring_boot.sys_usergroup_role</code>
     */
    public static final SysUsergroupRole SYS_USERGROUP_ROLE = new SysUsergroupRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysUsergroupRoleRecord> getRecordType() {
        return SysUsergroupRoleRecord.class;
    }

    /**
     * The column <code>spring_boot.sys_usergroup_role.roleId</code>.
     */
    public final TableField<SysUsergroupRoleRecord, String> ROLEID = createField("roleId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>spring_boot.sys_usergroup_role.roleCode</code>.
     */
    public final TableField<SysUsergroupRoleRecord, String> ROLECODE = createField("roleCode", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

    /**
     * The column <code>spring_boot.sys_usergroup_role.groupId</code>.
     */
    public final TableField<SysUsergroupRoleRecord, String> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>spring_boot.sys_usergroup_role</code> table reference
     */
    public SysUsergroupRole() {
        this("sys_usergroup_role", null);
    }

    /**
     * Create an aliased <code>spring_boot.sys_usergroup_role</code> table reference
     */
    public SysUsergroupRole(String alias) {
        this(alias, SYS_USERGROUP_ROLE);
    }

    private SysUsergroupRole(String alias, Table<SysUsergroupRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysUsergroupRole(String alias, Table<SysUsergroupRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "用户组与角色关系表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpringBoot.SPRING_BOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysUsergroupRoleRecord> getPrimaryKey() {
        return Keys.KEY_SYS_USERGROUP_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysUsergroupRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<SysUsergroupRoleRecord>>asList(Keys.KEY_SYS_USERGROUP_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUsergroupRole as(String alias) {
        return new SysUsergroupRole(alias, this);
    }

    /**
     * Rename this table
     */
    public SysUsergroupRole rename(String name) {
        return new SysUsergroupRole(name, null);
    }
}
