/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables;


import com.nanhu.model.sys.Keys;
import com.nanhu.model.sys.SpringBoot;
import com.nanhu.model.sys.tables.records.SysUserGroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户与用户组关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserGroup extends TableImpl<SysUserGroupRecord> {

    private static final long serialVersionUID = 1472565687;

    /**
     * The reference instance of <code>spring_boot.sys_user_group</code>
     */
    public static final SysUserGroup SYS_USER_GROUP = new SysUserGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysUserGroupRecord> getRecordType() {
        return SysUserGroupRecord.class;
    }

    /**
     * The column <code>spring_boot.sys_user_group.userId</code>.
     */
    public final TableField<SysUserGroupRecord, String> USERID = createField("userId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>spring_boot.sys_user_group.groupId</code>.
     */
    public final TableField<SysUserGroupRecord, String> GROUPID = createField("groupId", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>spring_boot.sys_user_group</code> table reference
     */
    public SysUserGroup() {
        this("sys_user_group", null);
    }

    /**
     * Create an aliased <code>spring_boot.sys_user_group</code> table reference
     */
    public SysUserGroup(String alias) {
        this(alias, SYS_USER_GROUP);
    }

    private SysUserGroup(String alias, Table<SysUserGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysUserGroup(String alias, Table<SysUserGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "用户与用户组关系表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SpringBoot.SPRING_BOOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysUserGroupRecord> getPrimaryKey() {
        return Keys.KEY_SYS_USER_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysUserGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<SysUserGroupRecord>>asList(Keys.KEY_SYS_USER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserGroup as(String alias) {
        return new SysUserGroup(alias, this);
    }

    /**
     * Rename this table
     */
    public SysUserGroup rename(String name) {
        return new SysUserGroup(name, null);
    }
}
