/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.story.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Story extends org.jooq.impl.TableImpl<com.nanhu.model.story.tables.records.StoryRecord> {

	private static final long serialVersionUID = -272588250;

	/**
	 * The singleton instance of <code>spring_boot.story</code>
	 */
	public static final com.nanhu.model.story.tables.Story STORY = new com.nanhu.model.story.tables.Story();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nanhu.model.story.tables.records.StoryRecord> getRecordType() {
		return com.nanhu.model.story.tables.records.StoryRecord.class;
	}

	/**
	 * The column <code>spring_boot.story.id</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>spring_boot.story.plot</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.lang.String> PLOT = createField("plot", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>spring_boot.story.writer</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.lang.String> WRITER = createField("writer", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>spring_boot.story.upvotes</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.lang.Long> UPVOTES = createField("upvotes", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>spring_boot.story.createdBy</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.lang.String> CREATEDBY = createField("createdBy", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>spring_boot.story.updatedBy</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.lang.String> UPDATEDBY = createField("updatedBy", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>spring_boot.story.createdDate</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.sql.Timestamp> CREATEDDATE = createField("createdDate", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>spring_boot.story.updatedDate</code>.
	 */
	public final org.jooq.TableField<com.nanhu.model.story.tables.records.StoryRecord, java.sql.Timestamp> UPDATEDDATE = createField("updatedDate", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>spring_boot.story</code> table reference
	 */
	public Story() {
		this("story", null);
	}

	/**
	 * Create an aliased <code>spring_boot.story</code> table reference
	 */
	public Story(java.lang.String alias) {
		this(alias, com.nanhu.model.story.tables.Story.STORY);
	}

	private Story(java.lang.String alias, org.jooq.Table<com.nanhu.model.story.tables.records.StoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Story(java.lang.String alias, org.jooq.Table<com.nanhu.model.story.tables.records.StoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nanhu.model.story.SpringBoot.SPRING_BOOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nanhu.model.story.tables.records.StoryRecord> getPrimaryKey() {
		return com.nanhu.model.story.Keys.KEY_STORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nanhu.model.story.tables.records.StoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nanhu.model.story.tables.records.StoryRecord>>asList(com.nanhu.model.story.Keys.KEY_STORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nanhu.model.story.tables.Story as(java.lang.String alias) {
		return new com.nanhu.model.story.tables.Story(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nanhu.model.story.tables.Story rename(java.lang.String name) {
		return new com.nanhu.model.story.tables.Story(name, null);
	}
}
