/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 部门
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDepartment implements Serializable {

    private static final long serialVersionUID = 966643296;

    private String    id;
    private String    depcode;
    private String    depname;
    private String    orgid;
    private String    orgcode;
    private String    depparentid;
    private Byte      status;
    private Byte      sort;
    private String    creator;
    private String    modifier;
    private Timestamp createdate;
    private Timestamp modifydate;
    private String    remark;

    public SysDepartment() {}

    public SysDepartment(SysDepartment value) {
        this.id = value.id;
        this.depcode = value.depcode;
        this.depname = value.depname;
        this.orgid = value.orgid;
        this.orgcode = value.orgcode;
        this.depparentid = value.depparentid;
        this.status = value.status;
        this.sort = value.sort;
        this.creator = value.creator;
        this.modifier = value.modifier;
        this.createdate = value.createdate;
        this.modifydate = value.modifydate;
        this.remark = value.remark;
    }

    public SysDepartment(
        String    id,
        String    depcode,
        String    depname,
        String    orgid,
        String    orgcode,
        String    depparentid,
        Byte      status,
        Byte      sort,
        String    creator,
        String    modifier,
        Timestamp createdate,
        Timestamp modifydate,
        String    remark
    ) {
        this.id = id;
        this.depcode = depcode;
        this.depname = depname;
        this.orgid = orgid;
        this.orgcode = orgcode;
        this.depparentid = depparentid;
        this.status = status;
        this.sort = sort;
        this.creator = creator;
        this.modifier = modifier;
        this.createdate = createdate;
        this.modifydate = modifydate;
        this.remark = remark;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDepcode() {
        return this.depcode;
    }

    public void setDepcode(String depcode) {
        this.depcode = depcode;
    }

    public String getDepname() {
        return this.depname;
    }

    public void setDepname(String depname) {
        this.depname = depname;
    }

    public String getOrgid() {
        return this.orgid;
    }

    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    public String getOrgcode() {
        return this.orgcode;
    }

    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    public String getDepparentid() {
        return this.depparentid;
    }

    public void setDepparentid(String depparentid) {
        this.depparentid = depparentid;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getSort() {
        return this.sort;
    }

    public void setSort(Byte sort) {
        this.sort = sort;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public Timestamp getModifydate() {
        return this.modifydate;
    }

    public void setModifydate(Timestamp modifydate) {
        this.modifydate = modifydate;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDepartment (");

        sb.append(id);
        sb.append(", ").append(depcode);
        sb.append(", ").append(depname);
        sb.append(", ").append(orgid);
        sb.append(", ").append(orgcode);
        sb.append(", ").append(depparentid);
        sb.append(", ").append(status);
        sb.append(", ").append(sort);
        sb.append(", ").append(creator);
        sb.append(", ").append(modifier);
        sb.append(", ").append(createdate);
        sb.append(", ").append(modifydate);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
