/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuCopy implements Serializable {

    private static final long serialVersionUID = 1814234174;

    private String    id;
    private String    moduleid;
    private String    menuname;
    private String    menuparentid;
    private String    menucode;
    private Byte      level;
    private String    menuhref;
    private String    menuicon;
    private Byte      status;
    private Byte      sort;
    private String    creator;
    private String    modifier;
    private Timestamp createdate;
    private Timestamp modifydate;
    private String    remark;

    public SysMenuCopy() {}

    public SysMenuCopy(SysMenuCopy value) {
        this.id = value.id;
        this.moduleid = value.moduleid;
        this.menuname = value.menuname;
        this.menuparentid = value.menuparentid;
        this.menucode = value.menucode;
        this.level = value.level;
        this.menuhref = value.menuhref;
        this.menuicon = value.menuicon;
        this.status = value.status;
        this.sort = value.sort;
        this.creator = value.creator;
        this.modifier = value.modifier;
        this.createdate = value.createdate;
        this.modifydate = value.modifydate;
        this.remark = value.remark;
    }

    public SysMenuCopy(
        String    id,
        String    moduleid,
        String    menuname,
        String    menuparentid,
        String    menucode,
        Byte      level,
        String    menuhref,
        String    menuicon,
        Byte      status,
        Byte      sort,
        String    creator,
        String    modifier,
        Timestamp createdate,
        Timestamp modifydate,
        String    remark
    ) {
        this.id = id;
        this.moduleid = moduleid;
        this.menuname = menuname;
        this.menuparentid = menuparentid;
        this.menucode = menucode;
        this.level = level;
        this.menuhref = menuhref;
        this.menuicon = menuicon;
        this.status = status;
        this.sort = sort;
        this.creator = creator;
        this.modifier = modifier;
        this.createdate = createdate;
        this.modifydate = modifydate;
        this.remark = remark;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getModuleid() {
        return this.moduleid;
    }

    public void setModuleid(String moduleid) {
        this.moduleid = moduleid;
    }

    public String getMenuname() {
        return this.menuname;
    }

    public void setMenuname(String menuname) {
        this.menuname = menuname;
    }

    public String getMenuparentid() {
        return this.menuparentid;
    }

    public void setMenuparentid(String menuparentid) {
        this.menuparentid = menuparentid;
    }

    public String getMenucode() {
        return this.menucode;
    }

    public void setMenucode(String menucode) {
        this.menucode = menucode;
    }

    public Byte getLevel() {
        return this.level;
    }

    public void setLevel(Byte level) {
        this.level = level;
    }

    public String getMenuhref() {
        return this.menuhref;
    }

    public void setMenuhref(String menuhref) {
        this.menuhref = menuhref;
    }

    public String getMenuicon() {
        return this.menuicon;
    }

    public void setMenuicon(String menuicon) {
        this.menuicon = menuicon;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getSort() {
        return this.sort;
    }

    public void setSort(Byte sort) {
        this.sort = sort;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public Timestamp getModifydate() {
        return this.modifydate;
    }

    public void setModifydate(Timestamp modifydate) {
        this.modifydate = modifydate;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysMenuCopy (");

        sb.append(id);
        sb.append(", ").append(moduleid);
        sb.append(", ").append(menuname);
        sb.append(", ").append(menuparentid);
        sb.append(", ").append(menucode);
        sb.append(", ").append(level);
        sb.append(", ").append(menuhref);
        sb.append(", ").append(menuicon);
        sb.append(", ").append(status);
        sb.append(", ").append(sort);
        sb.append(", ").append(creator);
        sb.append(", ").append(modifier);
        sb.append(", ").append(createdate);
        sb.append(", ").append(modifydate);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
