/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrganization implements Serializable {

    private static final long serialVersionUID = -1913987701;

    private String    id;
    private String    orgname;
    private String    orgcode;
    private String    orgparentid;
    private Byte      isindependent;
    private Byte      isvirtualaccounts;
    private Integer   orglevel;
    private Byte      status;
    private Byte      sort;
    private String    creator;
    private String    modifier;
    private Timestamp createdate;
    private Timestamp modifydate;
    private String    remark;

    public SysOrganization() {}

    public SysOrganization(SysOrganization value) {
        this.id = value.id;
        this.orgname = value.orgname;
        this.orgcode = value.orgcode;
        this.orgparentid = value.orgparentid;
        this.isindependent = value.isindependent;
        this.isvirtualaccounts = value.isvirtualaccounts;
        this.orglevel = value.orglevel;
        this.status = value.status;
        this.sort = value.sort;
        this.creator = value.creator;
        this.modifier = value.modifier;
        this.createdate = value.createdate;
        this.modifydate = value.modifydate;
        this.remark = value.remark;
    }

    public SysOrganization(
        String    id,
        String    orgname,
        String    orgcode,
        String    orgparentid,
        Byte      isindependent,
        Byte      isvirtualaccounts,
        Integer   orglevel,
        Byte      status,
        Byte      sort,
        String    creator,
        String    modifier,
        Timestamp createdate,
        Timestamp modifydate,
        String    remark
    ) {
        this.id = id;
        this.orgname = orgname;
        this.orgcode = orgcode;
        this.orgparentid = orgparentid;
        this.isindependent = isindependent;
        this.isvirtualaccounts = isvirtualaccounts;
        this.orglevel = orglevel;
        this.status = status;
        this.sort = sort;
        this.creator = creator;
        this.modifier = modifier;
        this.createdate = createdate;
        this.modifydate = modifydate;
        this.remark = remark;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOrgname() {
        return this.orgname;
    }

    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    public String getOrgcode() {
        return this.orgcode;
    }

    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    public String getOrgparentid() {
        return this.orgparentid;
    }

    public void setOrgparentid(String orgparentid) {
        this.orgparentid = orgparentid;
    }

    public Byte getIsindependent() {
        return this.isindependent;
    }

    public void setIsindependent(Byte isindependent) {
        this.isindependent = isindependent;
    }

    public Byte getIsvirtualaccounts() {
        return this.isvirtualaccounts;
    }

    public void setIsvirtualaccounts(Byte isvirtualaccounts) {
        this.isvirtualaccounts = isvirtualaccounts;
    }

    public Integer getOrglevel() {
        return this.orglevel;
    }

    public void setOrglevel(Integer orglevel) {
        this.orglevel = orglevel;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getSort() {
        return this.sort;
    }

    public void setSort(Byte sort) {
        this.sort = sort;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public Timestamp getModifydate() {
        return this.modifydate;
    }

    public void setModifydate(Timestamp modifydate) {
        this.modifydate = modifydate;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysOrganization (");

        sb.append(id);
        sb.append(", ").append(orgname);
        sb.append(", ").append(orgcode);
        sb.append(", ").append(orgparentid);
        sb.append(", ").append(isindependent);
        sb.append(", ").append(isvirtualaccounts);
        sb.append(", ").append(orglevel);
        sb.append(", ").append(status);
        sb.append(", ").append(sort);
        sb.append(", ").append(creator);
        sb.append(", ").append(modifier);
        sb.append(", ").append(createdate);
        sb.append(", ").append(modifydate);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
