/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionRole implements Serializable {

    private static final long serialVersionUID = -916748203;

    private String roleid;
    private String rolecode;
    private String resourcesid;

    public SysPermissionRole() {}

    public SysPermissionRole(SysPermissionRole value) {
        this.roleid = value.roleid;
        this.rolecode = value.rolecode;
        this.resourcesid = value.resourcesid;
    }

    public SysPermissionRole(
        String roleid,
        String rolecode,
        String resourcesid
    ) {
        this.roleid = roleid;
        this.rolecode = rolecode;
        this.resourcesid = resourcesid;
    }

    public String getRoleid() {
        return this.roleid;
    }

    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    public String getRolecode() {
        return this.rolecode;
    }

    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }

    public String getResourcesid() {
        return this.resourcesid;
    }

    public void setResourcesid(String resourcesid) {
        this.resourcesid = resourcesid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysPermissionRole (");

        sb.append(roleid);
        sb.append(", ").append(rolecode);
        sb.append(", ").append(resourcesid);

        sb.append(")");
        return sb.toString();
    }
}
