/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 权限操作关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionFunoperation implements Serializable {

    private static final long serialVersionUID = 166365913;

    private String funid;
    private String resourcesid;

    public SysPermissionFunoperation() {}

    public SysPermissionFunoperation(SysPermissionFunoperation value) {
        this.funid = value.funid;
        this.resourcesid = value.resourcesid;
    }

    public SysPermissionFunoperation(
        String funid,
        String resourcesid
    ) {
        this.funid = funid;
        this.resourcesid = resourcesid;
    }

    public String getFunid() {
        return this.funid;
    }

    public void setFunid(String funid) {
        this.funid = funid;
    }

    public String getResourcesid() {
        return this.resourcesid;
    }

    public void setResourcesid(String resourcesid) {
        this.resourcesid = resourcesid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysPermissionFunoperation (");

        sb.append(funid);
        sb.append(", ").append(resourcesid);

        sb.append(")");
        return sb.toString();
    }
}
