/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 权限用户关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionUser implements Serializable {

    private static final long serialVersionUID = -729409487;

    private String userid;
    private String resourcesid;

    public SysPermissionUser() {}

    public SysPermissionUser(SysPermissionUser value) {
        this.userid = value.userid;
        this.resourcesid = value.resourcesid;
    }

    public SysPermissionUser(
        String userid,
        String resourcesid
    ) {
        this.userid = userid;
        this.resourcesid = resourcesid;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getResourcesid() {
        return this.resourcesid;
    }

    public void setResourcesid(String resourcesid) {
        this.resourcesid = resourcesid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysPermissionUser (");

        sb.append(userid);
        sb.append(", ").append(resourcesid);

        sb.append(")");
        return sb.toString();
    }
}
