/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionMenu implements Serializable {

    private static final long serialVersionUID = -169902473;

    private String menuid;
    private String resourcesid;

    public SysPermissionMenu() {}

    public SysPermissionMenu(SysPermissionMenu value) {
        this.menuid = value.menuid;
        this.resourcesid = value.resourcesid;
    }

    public SysPermissionMenu(
        String menuid,
        String resourcesid
    ) {
        this.menuid = menuid;
        this.resourcesid = resourcesid;
    }

    public String getMenuid() {
        return this.menuid;
    }

    public void setMenuid(String menuid) {
        this.menuid = menuid;
    }

    public String getResourcesid() {
        return this.resourcesid;
    }

    public void setResourcesid(String resourcesid) {
        this.resourcesid = resourcesid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysPermissionMenu (");

        sb.append(menuid);
        sb.append(", ").append(resourcesid);

        sb.append(")");
        return sb.toString();
    }
}
