/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 子系统模块
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysSubsystemModule implements Serializable {

    private static final long serialVersionUID = 682132243;

    private String    id;
    private String    subsystemid;
    private String    modulename;
    private String    modulecode;
    private String    moduleparentid;
    private Byte      status;
    private Byte      sort;
    private String    creator;
    private String    modifier;
    private Timestamp createdate;
    private Timestamp modifydate;
    private String    remark;

    public SysSubsystemModule() {}

    public SysSubsystemModule(SysSubsystemModule value) {
        this.id = value.id;
        this.subsystemid = value.subsystemid;
        this.modulename = value.modulename;
        this.modulecode = value.modulecode;
        this.moduleparentid = value.moduleparentid;
        this.status = value.status;
        this.sort = value.sort;
        this.creator = value.creator;
        this.modifier = value.modifier;
        this.createdate = value.createdate;
        this.modifydate = value.modifydate;
        this.remark = value.remark;
    }

    public SysSubsystemModule(
        String    id,
        String    subsystemid,
        String    modulename,
        String    modulecode,
        String    moduleparentid,
        Byte      status,
        Byte      sort,
        String    creator,
        String    modifier,
        Timestamp createdate,
        Timestamp modifydate,
        String    remark
    ) {
        this.id = id;
        this.subsystemid = subsystemid;
        this.modulename = modulename;
        this.modulecode = modulecode;
        this.moduleparentid = moduleparentid;
        this.status = status;
        this.sort = sort;
        this.creator = creator;
        this.modifier = modifier;
        this.createdate = createdate;
        this.modifydate = modifydate;
        this.remark = remark;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSubsystemid() {
        return this.subsystemid;
    }

    public void setSubsystemid(String subsystemid) {
        this.subsystemid = subsystemid;
    }

    public String getModulename() {
        return this.modulename;
    }

    public void setModulename(String modulename) {
        this.modulename = modulename;
    }

    public String getModulecode() {
        return this.modulecode;
    }

    public void setModulecode(String modulecode) {
        this.modulecode = modulecode;
    }

    public String getModuleparentid() {
        return this.moduleparentid;
    }

    public void setModuleparentid(String moduleparentid) {
        this.moduleparentid = moduleparentid;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getSort() {
        return this.sort;
    }

    public void setSort(Byte sort) {
        this.sort = sort;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Timestamp getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Timestamp createdate) {
        this.createdate = createdate;
    }

    public Timestamp getModifydate() {
        return this.modifydate;
    }

    public void setModifydate(Timestamp modifydate) {
        this.modifydate = modifydate;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysSubsystemModule (");

        sb.append(id);
        sb.append(", ").append(subsystemid);
        sb.append(", ").append(modulename);
        sb.append(", ").append(modulecode);
        sb.append(", ").append(moduleparentid);
        sb.append(", ").append(status);
        sb.append(", ").append(sort);
        sb.append(", ").append(creator);
        sb.append(", ").append(modifier);
        sb.append(", ").append(createdate);
        sb.append(", ").append(modifydate);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
