/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 用户组与角色关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUsergroupRole implements Serializable {

    private static final long serialVersionUID = 1992310429;

    private String roleid;
    private String rolecode;
    private String groupid;

    public SysUsergroupRole() {}

    public SysUsergroupRole(SysUsergroupRole value) {
        this.roleid = value.roleid;
        this.rolecode = value.rolecode;
        this.groupid = value.groupid;
    }

    public SysUsergroupRole(
        String roleid,
        String rolecode,
        String groupid
    ) {
        this.roleid = roleid;
        this.rolecode = rolecode;
        this.groupid = groupid;
    }

    public String getRoleid() {
        return this.roleid;
    }

    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    public String getRolecode() {
        return this.rolecode;
    }

    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }

    public String getGroupid() {
        return this.groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUsergroupRole (");

        sb.append(roleid);
        sb.append(", ").append(rolecode);
        sb.append(", ").append(groupid);

        sb.append(")");
        return sb.toString();
    }
}
