/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysGroup;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 组
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysGroupRecord extends UpdatableRecordImpl<SysGroupRecord> implements Record10<String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1217753019;

    /**
     * Setter for <code>spring_boot.sys_group.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_group.groupName</code>.
     */
    public void setGroupname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.groupName</code>.
     */
    public String getGroupname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_group.groupParentId</code>.
     */
    public void setGroupparentid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.groupParentId</code>.
     */
    public String getGroupparentid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_group.status</code>.
     */
    public void setStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_group.sort</code>.
     */
    public void setSort(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.sort</code>.
     */
    public Byte getSort() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_group.creator</code>.
     */
    public void setCreator(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.creator</code>.
     */
    public String getCreator() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_group.modifier</code>.
     */
    public void setModifier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.modifier</code>.
     */
    public String getModifier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_group.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_group.modifyDate</code>.
     */
    public void setModifydate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.modifyDate</code>.
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>spring_boot.sys_group.remark</code>.
     */
    public void setRemark(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>spring_boot.sys_group.remark</code>.
     */
    public String getRemark() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysGroup.SYS_GROUP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysGroup.SYS_GROUP.GROUPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysGroup.SYS_GROUP.GROUPPARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return SysGroup.SYS_GROUP.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return SysGroup.SYS_GROUP.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysGroup.SYS_GROUP.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysGroup.SYS_GROUP.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SysGroup.SYS_GROUP.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SysGroup.SYS_GROUP.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysGroup.SYS_GROUP.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGroupname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupparentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value2(String value) {
        setGroupname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value3(String value) {
        setGroupparentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value4(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value5(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value6(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value7(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value8(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value9(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord value10(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysGroupRecord values(String value1, String value2, String value3, Byte value4, Byte value5, String value6, String value7, Timestamp value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysGroupRecord
     */
    public SysGroupRecord() {
        super(SysGroup.SYS_GROUP);
    }

    /**
     * Create a detached, initialised SysGroupRecord
     */
    public SysGroupRecord(String id, String groupname, String groupparentid, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysGroup.SYS_GROUP);

        set(0, id);
        set(1, groupname);
        set(2, groupparentid);
        set(3, status);
        set(4, sort);
        set(5, creator);
        set(6, modifier);
        set(7, createdate);
        set(8, modifydate);
        set(9, remark);
    }
}
