/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysLoginLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * 用户登录日志
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLoginLogRecord extends TableRecordImpl<SysLoginLogRecord> implements Record9<String, String, String, Timestamp, Long, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -894653200;

    /**
     * Setter for <code>spring_boot.sys_login_log.id</code>. id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.id</code>. id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.userId</code>. 登录用户UserId
     */
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.userId</code>. 登录用户UserId
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.loginIp</code>.
     */
    public void setLoginip(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.loginIp</code>.
     */
    public String getLoginip() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.loginDate</code>. 登录时间
     */
    public void setLogindate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.loginDate</code>. 登录时间
     */
    public Timestamp getLogindate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.expireTime</code>. 过期时间
     */
    public void setExpiretime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.expireTime</code>. 过期时间
     */
    public Long getExpiretime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.createBy</code>.
     */
    public void setCreateby(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.createBy</code>.
     */
    public String getCreateby() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.updateBy</code>.
     */
    public void setUpdateby(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.updateBy</code>.
     */
    public String getUpdateby() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_login_log.updateDate</code>.
     */
    public void setUpdatedate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_log.updateDate</code>.
     */
    public Timestamp getUpdatedate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Timestamp, Long, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Timestamp, Long, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysLoginLog.SYS_LOGIN_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysLoginLog.SYS_LOGIN_LOG.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysLoginLog.SYS_LOGIN_LOG.LOGINIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return SysLoginLog.SYS_LOGIN_LOG.LOGINDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SysLoginLog.SYS_LOGIN_LOG.EXPIRETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysLoginLog.SYS_LOGIN_LOG.CREATEBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysLoginLog.SYS_LOGIN_LOG.UPDATEBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SysLoginLog.SYS_LOGIN_LOG.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SysLoginLog.SYS_LOGIN_LOG.UPDATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLoginip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLogindate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getExpiretime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreateby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUpdateby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value2(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value3(String value) {
        setLoginip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value4(Timestamp value) {
        setLogindate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value5(Long value) {
        setExpiretime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value6(String value) {
        setCreateby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value7(String value) {
        setUpdateby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value8(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord value9(Timestamp value) {
        setUpdatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginLogRecord values(String value1, String value2, String value3, Timestamp value4, Long value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLoginLogRecord
     */
    public SysLoginLogRecord() {
        super(SysLoginLog.SYS_LOGIN_LOG);
    }

    /**
     * Create a detached, initialised SysLoginLogRecord
     */
    public SysLoginLogRecord(String id, String userid, String loginip, Timestamp logindate, Long expiretime, String createby, String updateby, Timestamp createdate, Timestamp updatedate) {
        super(SysLoginLog.SYS_LOGIN_LOG);

        set(0, id);
        set(1, userid);
        set(2, loginip);
        set(3, logindate);
        set(4, expiretime);
        set(5, createby);
        set(6, updateby);
        set(7, createdate);
        set(8, updatedate);
    }
}
