/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 操作日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLogRecord extends UpdatableRecordImpl<SysLogRecord> implements Record5<String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -170010243;

    /**
     * Setter for <code>spring_boot.sys_log.id</code>. 日志ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_log.id</code>. 日志ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_log.operationName</code>. 操作类型
     */
    public void setOperationname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_log.operationName</code>. 操作类型
     */
    public String getOperationname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_log.operationContent</code>. 操作内容
     */
    public void setOperationcontent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_log.operationContent</code>. 操作内容
     */
    public String getOperationcontent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_log.operationUser</code>. 操作人
     */
    public void setOperationuser(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_log.operationUser</code>. 操作人
     */
    public String getOperationuser() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_log.operationDate</code>. 操作时间
     */
    public void setOperationdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_log.operationDate</code>. 操作时间
     */
    public Timestamp getOperationdate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysLog.SYS_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysLog.SYS_LOG.OPERATIONNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysLog.SYS_LOG.OPERATIONCONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysLog.SYS_LOG.OPERATIONUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SysLog.SYS_LOG.OPERATIONDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOperationname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOperationcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOperationuser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getOperationdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value2(String value) {
        setOperationname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value3(String value) {
        setOperationcontent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value4(String value) {
        setOperationuser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value5(Timestamp value) {
        setOperationdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord values(String value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLogRecord
     */
    public SysLogRecord() {
        super(SysLog.SYS_LOG);
    }

    /**
     * Create a detached, initialised SysLogRecord
     */
    public SysLogRecord(String id, String operationname, String operationcontent, String operationuser, Timestamp operationdate) {
        super(SysLog.SYS_LOG);

        set(0, id);
        set(1, operationname);
        set(2, operationcontent);
        set(3, operationuser);
        set(4, operationdate);
    }
}
