/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysLoginUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLoginUserRecord extends UpdatableRecordImpl<SysLoginUserRecord> implements Record15<String, String, String, String, String, String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1250356282;

    /**
     * Setter for <code>spring_boot.sys_login_user.id</code>. id
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.id</code>. id
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.groupId</code>. 组ID
     */
    public void setGroupid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.groupId</code>. 组ID
     */
    public String getGroupid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.loginName</code>. 登录名
     */
    public void setLoginname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.loginName</code>. 登录名
     */
    public String getLoginname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.userName</code>. 用户名称
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.userName</code>. 用户名称
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.mobile</code>. 手机号码
     */
    public void setMobile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.mobile</code>. 手机号码
     */
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.salt</code>. 密钥
     */
    public void setSalt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.salt</code>. 密钥
     */
    public String getSalt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.status</code>. 状态(99：删除,10：启用 ,20：禁用 30临时)
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.status</code>. 状态(99：删除,10：启用 ,20：禁用 30临时)
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.sort</code>. 排序
     */
    public void setSort(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.sort</code>. 排序
     */
    public Byte getSort() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.creator</code>. 创建用户Id
     */
    public void setCreator(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.creator</code>. 创建用户Id
     */
    public String getCreator() {
        return (String) get(10);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.modifier</code>. 修改用户Id
     */
    public void setModifier(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.modifier</code>. 修改用户Id
     */
    public String getModifier() {
        return (String) get(11);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.createDate</code>. 创建时间
     */
    public void setCreatedate(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.createDate</code>. 创建时间
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.modifyDate</code>. 修改时间
     */
    public void setModifydate(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.modifyDate</code>. 修改时间
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>spring_boot.sys_login_user.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>spring_boot.sys_login_user.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysLoginUser.SYS_LOGIN_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysLoginUser.SYS_LOGIN_USER.GROUPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysLoginUser.SYS_LOGIN_USER.LOGINNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysLoginUser.SYS_LOGIN_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysLoginUser.SYS_LOGIN_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysLoginUser.SYS_LOGIN_USER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysLoginUser.SYS_LOGIN_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysLoginUser.SYS_LOGIN_USER.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return SysLoginUser.SYS_LOGIN_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return SysLoginUser.SYS_LOGIN_USER.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysLoginUser.SYS_LOGIN_USER.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SysLoginUser.SYS_LOGIN_USER.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return SysLoginUser.SYS_LOGIN_USER.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return SysLoginUser.SYS_LOGIN_USER.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return SysLoginUser.SYS_LOGIN_USER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGroupid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLoginname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value2(String value) {
        setGroupid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value3(String value) {
        setLoginname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value6(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value7(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value8(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value10(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value11(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value12(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value13(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value14(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord value15(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLoginUserRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Byte value9, Byte value10, String value11, String value12, Timestamp value13, Timestamp value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLoginUserRecord
     */
    public SysLoginUserRecord() {
        super(SysLoginUser.SYS_LOGIN_USER);
    }

    /**
     * Create a detached, initialised SysLoginUserRecord
     */
    public SysLoginUserRecord(String id, String groupid, String loginname, String password, String username, String mobile, String email, String salt, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysLoginUser.SYS_LOGIN_USER);

        set(0, id);
        set(1, groupid);
        set(2, loginname);
        set(3, password);
        set(4, username);
        set(5, mobile);
        set(6, email);
        set(7, salt);
        set(8, status);
        set(9, sort);
        set(10, creator);
        set(11, modifier);
        set(12, createdate);
        set(13, modifydate);
        set(14, remark);
    }
}
