/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysMember;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * 组织成员关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMemberRecord extends TableRecordImpl<SysMemberRecord> implements Record14<String, String, String, String, String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -1799174125;

    /**
     * Setter for <code>spring_boot.sys_member.id</code>. 成员ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.id</code>. 成员ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_member.userId</code>. 用户ID
     */
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.userId</code>. 用户ID
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_member.orgId</code>. 组织机构ID
     */
    public void setOrgid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.orgId</code>. 组织机构ID
     */
    public String getOrgid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_member.positionId</code>. 职位ID
     */
    public void setPositionid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.positionId</code>. 职位ID
     */
    public String getPositionid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_member.depId</code>. 部门(组)ID
     */
    public void setDepid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.depId</code>. 部门(组)ID
     */
    public String getDepid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_member.roleId</code>. 角色ID
     */
    public void setRoleid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.roleId</code>. 角色ID
     */
    public String getRoleid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_member.roleCode</code>. 角色编码
     */
    public void setRolecode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.roleCode</code>. 角色编码
     */
    public String getRolecode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_member.status</code>. 状态(99：删除,10：启用 ,20：禁用)
     */
    public void setStatus(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.status</code>. 状态(99：删除,10：启用 ,20：禁用)
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_member.sort</code>. 排序
     */
    public void setSort(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.sort</code>. 排序
     */
    public Byte getSort() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>spring_boot.sys_member.creator</code>. 创建用户Id
     */
    public void setCreator(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.creator</code>. 创建用户Id
     */
    public String getCreator() {
        return (String) get(9);
    }

    /**
     * Setter for <code>spring_boot.sys_member.modifier</code>. 修改用户Id
     */
    public void setModifier(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.modifier</code>. 修改用户Id
     */
    public String getModifier() {
        return (String) get(10);
    }

    /**
     * Setter for <code>spring_boot.sys_member.createDate</code>. 创建时间
     */
    public void setCreatedate(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.createDate</code>. 创建时间
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>spring_boot.sys_member.modifyDate</code>. 修改时间
     */
    public void setModifydate(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.modifyDate</code>. 修改时间
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>spring_boot.sys_member.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>spring_boot.sys_member.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysMember.SYS_MEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysMember.SYS_MEMBER.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysMember.SYS_MEMBER.ORGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysMember.SYS_MEMBER.POSITIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysMember.SYS_MEMBER.DEPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysMember.SYS_MEMBER.ROLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysMember.SYS_MEMBER.ROLECODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return SysMember.SYS_MEMBER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return SysMember.SYS_MEMBER.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysMember.SYS_MEMBER.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysMember.SYS_MEMBER.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return SysMember.SYS_MEMBER.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return SysMember.SYS_MEMBER.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return SysMember.SYS_MEMBER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPositionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDepid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRoleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRolecode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value2(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value3(String value) {
        setOrgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value4(String value) {
        setPositionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value5(String value) {
        setDepid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value6(String value) {
        setRoleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value7(String value) {
        setRolecode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value9(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value10(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value11(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value12(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value13(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord value14(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMemberRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Byte value8, Byte value9, String value10, String value11, Timestamp value12, Timestamp value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMemberRecord
     */
    public SysMemberRecord() {
        super(SysMember.SYS_MEMBER);
    }

    /**
     * Create a detached, initialised SysMemberRecord
     */
    public SysMemberRecord(String id, String userid, String orgid, String positionid, String depid, String roleid, String rolecode, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysMember.SYS_MEMBER);

        set(0, id);
        set(1, userid);
        set(2, orgid);
        set(3, positionid);
        set(4, depid);
        set(5, roleid);
        set(6, rolecode);
        set(7, status);
        set(8, sort);
        set(9, creator);
        set(10, modifier);
        set(11, createdate);
        set(12, modifydate);
        set(13, remark);
    }
}
