/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysMenu;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuRecord extends TableRecordImpl<SysMenuRecord> implements Record15<String, String, String, String, String, Byte, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1897264187;

    /**
     * Setter for <code>spring_boot.sys_menu.id</code>. 菜单ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.id</code>. 菜单ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.moduleId</code>. 子系统模块ID
     */
    public void setModuleid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.moduleId</code>. 子系统模块ID
     */
    public String getModuleid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.menuName</code>. 菜单名称
     */
    public void setMenuname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.menuName</code>. 菜单名称
     */
    public String getMenuname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.menuParentId</code>. 菜单父节点
     */
    public void setMenuparentid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.menuParentId</code>. 菜单父节点
     */
    public String getMenuparentid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.menuCode</code>. 菜单编码（MENU_ 开头）
     */
    public void setMenucode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.menuCode</code>. 菜单编码（MENU_ 开头）
     */
    public String getMenucode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.level</code>. 级别（最多四级）
     */
    public void setLevel(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.level</code>. 级别（最多四级）
     */
    public Byte getLevel() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.menuHref</code>. 访问路径
     */
    public void setMenuhref(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.menuHref</code>. 访问路径
     */
    public String getMenuhref() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.menuIcon</code>. 图标（关联图片文件管理表获取）
     */
    public void setMenuicon(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.menuIcon</code>. 图标（关联图片文件管理表获取）
     */
    public String getMenuicon() {
        return (String) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.status</code>. 状态(99：删除,10：启用 ,20：禁用)
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.status</code>. 状态(99：删除,10：启用 ,20：禁用)
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.sort</code>. 排序
     */
    public void setSort(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.sort</code>. 排序
     */
    public Byte getSort() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.creator</code>. 创建用户Id
     */
    public void setCreator(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.creator</code>. 创建用户Id
     */
    public String getCreator() {
        return (String) get(10);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.modifier</code>. 修改用户Id
     */
    public void setModifier(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.modifier</code>. 修改用户Id
     */
    public String getModifier() {
        return (String) get(11);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.createDate</code>. 创建时间
     */
    public void setCreatedate(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.createDate</code>. 创建时间
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.modifyDate</code>. 修改时间
     */
    public void setModifydate(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.modifyDate</code>. 修改时间
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>spring_boot.sys_menu.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>spring_boot.sys_menu.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, Byte, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, Byte, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysMenu.SYS_MENU.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysMenu.SYS_MENU.MODULEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysMenu.SYS_MENU.MENUNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysMenu.SYS_MENU.MENUPARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysMenu.SYS_MENU.MENUCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return SysMenu.SYS_MENU.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysMenu.SYS_MENU.MENUHREF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysMenu.SYS_MENU.MENUICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return SysMenu.SYS_MENU.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return SysMenu.SYS_MENU.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysMenu.SYS_MENU.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SysMenu.SYS_MENU.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return SysMenu.SYS_MENU.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return SysMenu.SYS_MENU.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return SysMenu.SYS_MENU.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getModuleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMenuname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMenuparentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMenucode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMenuhref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMenuicon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value2(String value) {
        setModuleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value3(String value) {
        setMenuname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value4(String value) {
        setMenuparentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value5(String value) {
        setMenucode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value6(Byte value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value7(String value) {
        setMenuhref(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value8(String value) {
        setMenuicon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value10(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value11(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value12(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value13(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value14(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value15(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, String value7, String value8, Byte value9, Byte value10, String value11, String value12, Timestamp value13, Timestamp value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMenuRecord
     */
    public SysMenuRecord() {
        super(SysMenu.SYS_MENU);
    }

    /**
     * Create a detached, initialised SysMenuRecord
     */
    public SysMenuRecord(String id, String moduleid, String menuname, String menuparentid, String menucode, Byte level, String menuhref, String menuicon, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysMenu.SYS_MENU);

        set(0, id);
        set(1, moduleid);
        set(2, menuname);
        set(3, menuparentid);
        set(4, menucode);
        set(5, level);
        set(6, menuhref);
        set(7, menuicon);
        set(8, status);
        set(9, sort);
        set(10, creator);
        set(11, modifier);
        set(12, createdate);
        set(13, modifydate);
        set(14, remark);
    }
}
