/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysOrgDepartmentPosition;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record3;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 组织部门与组织岗位
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrgDepartmentPositionRecord extends UpdatableRecordImpl<SysOrgDepartmentPositionRecord> implements Record10<String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1746757671;

    /**
     * Setter for <code>spring_boot.sys_org_department_position.orgId</code>.
     */
    public void setOrgid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.orgId</code>.
     */
    public String getOrgid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.positionId</code>.
     */
    public void setPositionid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.positionId</code>.
     */
    public String getPositionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.depId</code>.
     */
    public void setDepid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.depId</code>.
     */
    public String getDepid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.status</code>.
     */
    public void setStatus(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.sort</code>.
     */
    public void setSort(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.sort</code>.
     */
    public Byte getSort() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.creator</code>.
     */
    public void setCreator(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.creator</code>.
     */
    public String getCreator() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.modifier</code>.
     */
    public void setModifier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.modifier</code>.
     */
    public String getModifier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.modifyDate</code>.
     */
    public void setModifydate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.modifyDate</code>.
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>spring_boot.sys_org_department_position.remark</code>.
     */
    public void setRemark(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_department_position.remark</code>.
     */
    public String getRemark() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.ORGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.POSITIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.DEPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOrgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPositionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDepid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value1(String value) {
        setOrgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value2(String value) {
        setPositionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value3(String value) {
        setDepid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value4(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value5(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value6(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value7(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value8(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value9(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord value10(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgDepartmentPositionRecord values(String value1, String value2, String value3, Byte value4, Byte value5, String value6, String value7, Timestamp value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOrgDepartmentPositionRecord
     */
    public SysOrgDepartmentPositionRecord() {
        super(SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION);
    }

    /**
     * Create a detached, initialised SysOrgDepartmentPositionRecord
     */
    public SysOrgDepartmentPositionRecord(String orgid, String positionid, String depid, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION);

        set(0, orgid);
        set(1, positionid);
        set(2, depid);
        set(3, status);
        set(4, sort);
        set(5, creator);
        set(6, modifier);
        set(7, createdate);
        set(8, modifydate);
        set(9, remark);
    }
}
