/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysOrganization;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrganizationRecord extends TableRecordImpl<SysOrganizationRecord> implements Record14<String, String, String, String, Byte, Byte, Integer, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1428927431;

    /**
     * Setter for <code>spring_boot.sys_organization.id</code>. 组织机构ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.id</code>. 组织机构ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.orgName</code>. 组织机构名称
     */
    public void setOrgname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.orgName</code>. 组织机构名称
     */
    public String getOrgname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.orgCode</code>. 组织机构编码
     */
    public void setOrgcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.orgCode</code>. 组织机构编码
     */
    public String getOrgcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.orgParentId</code>. 组织机构父节点Id
     */
    public void setOrgparentid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.orgParentId</code>. 组织机构父节点Id
     */
    public String getOrgparentid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.isIndependent</code>. 是否独立核算(1：启用 ,0：禁用)
     */
    public void setIsindependent(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.isIndependent</code>. 是否独立核算(1：启用 ,0：禁用)
     */
    public Byte getIsindependent() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.isVirtualAccounts</code>. 是否独立虚拟账户(1：启用 ,0：禁用)
     */
    public void setIsvirtualaccounts(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.isVirtualAccounts</code>. 是否独立虚拟账户(1：启用 ,0：禁用)
     */
    public Byte getIsvirtualaccounts() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.orgLevel</code>. 组织级别（100：总部、888：平台、999、其他）
     */
    public void setOrglevel(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.orgLevel</code>. 组织级别（100：总部、888：平台、999、其他）
     */
    public Integer getOrglevel() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.status</code>. 状态状态(99：删除,10：启用 ,20：禁用)
     */
    public void setStatus(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.status</code>. 状态状态(99：删除,10：启用 ,20：禁用)
     */
    public Byte getStatus() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.sort</code>. 排序
     */
    public void setSort(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.sort</code>. 排序
     */
    public Byte getSort() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.creator</code>. 创建用户Id
     */
    public void setCreator(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.creator</code>. 创建用户Id
     */
    public String getCreator() {
        return (String) get(9);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.modifier</code>. 修改用户Id
     */
    public void setModifier(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.modifier</code>. 修改用户Id
     */
    public String getModifier() {
        return (String) get(10);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.createDate</code>. 创建时间
     */
    public void setCreatedate(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.createDate</code>. 创建时间
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.modifyDate</code>. 修改时间
     */
    public void setModifydate(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.modifyDate</code>. 修改时间
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>spring_boot.sys_organization.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>spring_boot.sys_organization.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, Byte, Byte, Integer, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, Byte, Byte, Integer, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysOrganization.SYS_ORGANIZATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysOrganization.SYS_ORGANIZATION.ORGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysOrganization.SYS_ORGANIZATION.ORGCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysOrganization.SYS_ORGANIZATION.ORGPARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return SysOrganization.SYS_ORGANIZATION.ISINDEPENDENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return SysOrganization.SYS_ORGANIZATION.ISVIRTUALACCOUNTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return SysOrganization.SYS_ORGANIZATION.ORGLEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return SysOrganization.SYS_ORGANIZATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return SysOrganization.SYS_ORGANIZATION.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysOrganization.SYS_ORGANIZATION.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysOrganization.SYS_ORGANIZATION.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return SysOrganization.SYS_ORGANIZATION.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return SysOrganization.SYS_ORGANIZATION.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return SysOrganization.SYS_ORGANIZATION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrgname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrgcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrgparentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsindependent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsvirtualaccounts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getOrglevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value2(String value) {
        setOrgname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value3(String value) {
        setOrgcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value4(String value) {
        setOrgparentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value5(Byte value) {
        setIsindependent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value6(Byte value) {
        setIsvirtualaccounts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value7(Integer value) {
        setOrglevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value8(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value9(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value10(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value11(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value12(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value13(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value14(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord values(String value1, String value2, String value3, String value4, Byte value5, Byte value6, Integer value7, Byte value8, Byte value9, String value10, String value11, Timestamp value12, Timestamp value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOrganizationRecord
     */
    public SysOrganizationRecord() {
        super(SysOrganization.SYS_ORGANIZATION);
    }

    /**
     * Create a detached, initialised SysOrganizationRecord
     */
    public SysOrganizationRecord(String id, String orgname, String orgcode, String orgparentid, Byte isindependent, Byte isvirtualaccounts, Integer orglevel, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysOrganization.SYS_ORGANIZATION);

        set(0, id);
        set(1, orgname);
        set(2, orgcode);
        set(3, orgparentid);
        set(4, isindependent);
        set(5, isvirtualaccounts);
        set(6, orglevel);
        set(7, status);
        set(8, sort);
        set(9, creator);
        set(10, modifier);
        set(11, createdate);
        set(12, modifydate);
        set(13, remark);
    }
}
