/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysOrgPosition;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 组织与职位
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrgPositionRecord extends UpdatableRecordImpl<SysOrgPositionRecord> implements Record9<String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 2087899919;

    /**
     * Setter for <code>spring_boot.sys_org_position.orgId</code>.
     */
    public void setOrgid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.orgId</code>.
     */
    public String getOrgid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.positionId</code>.
     */
    public void setPositionid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.positionId</code>.
     */
    public String getPositionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.status</code>.
     */
    public void setStatus(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.sort</code>.
     */
    public void setSort(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.sort</code>.
     */
    public Byte getSort() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.creator</code>.
     */
    public void setCreator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.creator</code>.
     */
    public String getCreator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.modifier</code>.
     */
    public void setModifier(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.modifier</code>.
     */
    public String getModifier() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.createDate</code>.
     */
    public void setCreatedate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.createDate</code>.
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.modifyDate</code>.
     */
    public void setModifydate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.modifyDate</code>.
     */
    public Timestamp getModifydate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>spring_boot.sys_org_position.remark</code>.
     */
    public void setRemark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring_boot.sys_org_position.remark</code>.
     */
    public String getRemark() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, Byte, Byte, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysOrgPosition.SYS_ORG_POSITION.ORGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysOrgPosition.SYS_ORG_POSITION.POSITIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return SysOrgPosition.SYS_ORG_POSITION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return SysOrgPosition.SYS_ORG_POSITION.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysOrgPosition.SYS_ORG_POSITION.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysOrgPosition.SYS_ORG_POSITION.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return SysOrgPosition.SYS_ORG_POSITION.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SysOrgPosition.SYS_ORG_POSITION.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysOrgPosition.SYS_ORG_POSITION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOrgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPositionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value1(String value) {
        setOrgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value2(String value) {
        setPositionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value3(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value4(Byte value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value5(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value6(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value7(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value8(Timestamp value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord value9(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrgPositionRecord values(String value1, String value2, Byte value3, Byte value4, String value5, String value6, Timestamp value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOrgPositionRecord
     */
    public SysOrgPositionRecord() {
        super(SysOrgPosition.SYS_ORG_POSITION);
    }

    /**
     * Create a detached, initialised SysOrgPositionRecord
     */
    public SysOrgPositionRecord(String orgid, String positionid, Byte status, Byte sort, String creator, String modifier, Timestamp createdate, Timestamp modifydate, String remark) {
        super(SysOrgPosition.SYS_ORG_POSITION);

        set(0, orgid);
        set(1, positionid);
        set(2, status);
        set(3, sort);
        set(4, creator);
        set(5, modifier);
        set(6, createdate);
        set(7, modifydate);
        set(8, remark);
    }
}
