/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysPermissionGroup;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * 组权限表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionGroupRecord extends TableRecordImpl<SysPermissionGroupRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -687975738;

    /**
     * Setter for <code>spring_boot.sys_permission_group.groupId</code>. 组ID
     */
    public void setGroupid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_permission_group.groupId</code>. 组ID
     */
    public String getGroupid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_permission_group.resourcesId</code>. 资源ID
     */
    public void setResourcesid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_permission_group.resourcesId</code>. 资源ID
     */
    public String getResourcesid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysPermissionGroup.SYS_PERMISSION_GROUP.GROUPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysPermissionGroup.SYS_PERMISSION_GROUP.RESOURCESID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGroupid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getResourcesid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionGroupRecord value1(String value) {
        setGroupid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionGroupRecord value2(String value) {
        setResourcesid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionGroupRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysPermissionGroupRecord
     */
    public SysPermissionGroupRecord() {
        super(SysPermissionGroup.SYS_PERMISSION_GROUP);
    }

    /**
     * Create a detached, initialised SysPermissionGroupRecord
     */
    public SysPermissionGroupRecord(String groupid, String resourcesid) {
        super(SysPermissionGroup.SYS_PERMISSION_GROUP);

        set(0, groupid);
        set(1, resourcesid);
    }
}
