/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysPermissionMenu;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionMenuRecord extends TableRecordImpl<SysPermissionMenuRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1079438358;

    /**
     * Setter for <code>spring_boot.sys_permission_menu.menuId</code>. 菜单ID
     */
    public void setMenuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_permission_menu.menuId</code>. 菜单ID
     */
    public String getMenuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_permission_menu.resourcesId</code>. 资源ID
     */
    public void setResourcesid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_permission_menu.resourcesId</code>. 资源ID
     */
    public String getResourcesid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysPermissionMenu.SYS_PERMISSION_MENU.MENUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysPermissionMenu.SYS_PERMISSION_MENU.RESOURCESID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMenuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getResourcesid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionMenuRecord value1(String value) {
        setMenuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionMenuRecord value2(String value) {
        setResourcesid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysPermissionMenuRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysPermissionMenuRecord
     */
    public SysPermissionMenuRecord() {
        super(SysPermissionMenu.SYS_PERMISSION_MENU);
    }

    /**
     * Create a detached, initialised SysPermissionMenuRecord
     */
    public SysPermissionMenuRecord(String menuid, String resourcesid) {
        super(SysPermissionMenu.SYS_PERMISSION_MENU);

        set(0, menuid);
        set(1, resourcesid);
    }
}
