/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysUsergroupRole;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户组与角色关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUsergroupRoleRecord extends UpdatableRecordImpl<SysUsergroupRoleRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 52545822;

    /**
     * Setter for <code>spring_boot.sys_usergroup_role.roleId</code>.
     */
    public void setRoleid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_usergroup_role.roleId</code>.
     */
    public String getRoleid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_usergroup_role.roleCode</code>.
     */
    public void setRolecode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_usergroup_role.roleCode</code>.
     */
    public String getRolecode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring_boot.sys_usergroup_role.groupId</code>.
     */
    public void setGroupid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring_boot.sys_usergroup_role.groupId</code>.
     */
    public String getGroupid() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysUsergroupRole.SYS_USERGROUP_ROLE.ROLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysUsergroupRole.SYS_USERGROUP_ROLE.ROLECODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysUsergroupRole.SYS_USERGROUP_ROLE.GROUPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRoleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRolecode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUsergroupRoleRecord value1(String value) {
        setRoleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUsergroupRoleRecord value2(String value) {
        setRolecode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUsergroupRoleRecord value3(String value) {
        setGroupid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUsergroupRoleRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUsergroupRoleRecord
     */
    public SysUsergroupRoleRecord() {
        super(SysUsergroupRole.SYS_USERGROUP_ROLE);
    }

    /**
     * Create a detached, initialised SysUsergroupRoleRecord
     */
    public SysUsergroupRoleRecord(String roleid, String rolecode, String groupid) {
        super(SysUsergroupRole.SYS_USERGROUP_ROLE);

        set(0, roleid);
        set(1, rolecode);
        set(2, groupid);
    }
}
