/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys.tables.records;


import com.nanhu.model.sys.tables.SysUserGroup;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户与用户组关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserGroupRecord extends UpdatableRecordImpl<SysUserGroupRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1473852363;

    /**
     * Setter for <code>spring_boot.sys_user_group.userId</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_boot.sys_user_group.userId</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>spring_boot.sys_user_group.groupId</code>.
     */
    public void setGroupid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_boot.sys_user_group.groupId</code>.
     */
    public String getGroupid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysUserGroup.SYS_USER_GROUP.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysUserGroup.SYS_USER_GROUP.GROUPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGroupid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserGroupRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserGroupRecord value2(String value) {
        setGroupid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserGroupRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserGroupRecord
     */
    public SysUserGroupRecord() {
        super(SysUserGroup.SYS_USER_GROUP);
    }

    /**
     * Create a detached, initialised SysUserGroupRecord
     */
    public SysUserGroupRecord(String userid, String groupid) {
        super(SysUserGroup.SYS_USER_GROUP);

        set(0, userid);
        set(1, groupid);
    }
}
