/**
 * This class is generated by jOOQ
 */
package com.nanhu.model.sys;


import com.nanhu.model.sys.tables.SysFunctionoperation;
import com.nanhu.model.sys.tables.SysGroup;
import com.nanhu.model.sys.tables.SysLog;
import com.nanhu.model.sys.tables.SysLoginUser;
import com.nanhu.model.sys.tables.SysOrgDepartmentPosition;
import com.nanhu.model.sys.tables.SysOrgPosition;
import com.nanhu.model.sys.tables.SysPermissionFunoperation;
import com.nanhu.model.sys.tables.SysPosition;
import com.nanhu.model.sys.tables.SysSubsystem;
import com.nanhu.model.sys.tables.SysSubsystemModule;
import com.nanhu.model.sys.tables.SysUserGroup;
import com.nanhu.model.sys.tables.SysUsergroupRole;
import com.nanhu.model.sys.tables.records.SysFunctionoperationRecord;
import com.nanhu.model.sys.tables.records.SysGroupRecord;
import com.nanhu.model.sys.tables.records.SysLogRecord;
import com.nanhu.model.sys.tables.records.SysLoginUserRecord;
import com.nanhu.model.sys.tables.records.SysOrgDepartmentPositionRecord;
import com.nanhu.model.sys.tables.records.SysOrgPositionRecord;
import com.nanhu.model.sys.tables.records.SysPermissionFunoperationRecord;
import com.nanhu.model.sys.tables.records.SysPositionRecord;
import com.nanhu.model.sys.tables.records.SysSubsystemModuleRecord;
import com.nanhu.model.sys.tables.records.SysSubsystemRecord;
import com.nanhu.model.sys.tables.records.SysUserGroupRecord;
import com.nanhu.model.sys.tables.records.SysUsergroupRoleRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>spring_boot</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysFunctionoperationRecord> KEY_SYS_FUNCTIONOPERATION_PRIMARY = UniqueKeys0.KEY_SYS_FUNCTIONOPERATION_PRIMARY;
    public static final UniqueKey<SysGroupRecord> KEY_SYS_GROUP_PRIMARY = UniqueKeys0.KEY_SYS_GROUP_PRIMARY;
    public static final UniqueKey<SysLogRecord> KEY_SYS_LOG_PRIMARY = UniqueKeys0.KEY_SYS_LOG_PRIMARY;
    public static final UniqueKey<SysLoginUserRecord> KEY_SYS_LOGIN_USER_PRIMARY = UniqueKeys0.KEY_SYS_LOGIN_USER_PRIMARY;
    public static final UniqueKey<SysOrgDepartmentPositionRecord> KEY_SYS_ORG_DEPARTMENT_POSITION_PRIMARY = UniqueKeys0.KEY_SYS_ORG_DEPARTMENT_POSITION_PRIMARY;
    public static final UniqueKey<SysOrgPositionRecord> KEY_SYS_ORG_POSITION_PRIMARY = UniqueKeys0.KEY_SYS_ORG_POSITION_PRIMARY;
    public static final UniqueKey<SysPermissionFunoperationRecord> KEY_SYS_PERMISSION_FUNOPERATION_PRIMARY = UniqueKeys0.KEY_SYS_PERMISSION_FUNOPERATION_PRIMARY;
    public static final UniqueKey<SysPositionRecord> KEY_SYS_POSITION_PRIMARY = UniqueKeys0.KEY_SYS_POSITION_PRIMARY;
    public static final UniqueKey<SysSubsystemRecord> KEY_SYS_SUBSYSTEM_PRIMARY = UniqueKeys0.KEY_SYS_SUBSYSTEM_PRIMARY;
    public static final UniqueKey<SysSubsystemModuleRecord> KEY_SYS_SUBSYSTEM_MODULE_PRIMARY = UniqueKeys0.KEY_SYS_SUBSYSTEM_MODULE_PRIMARY;
    public static final UniqueKey<SysUsergroupRoleRecord> KEY_SYS_USERGROUP_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_USERGROUP_ROLE_PRIMARY;
    public static final UniqueKey<SysUserGroupRecord> KEY_SYS_USER_GROUP_PRIMARY = UniqueKeys0.KEY_SYS_USER_GROUP_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<SysFunctionoperationRecord> KEY_SYS_FUNCTIONOPERATION_PRIMARY = createUniqueKey(SysFunctionoperation.SYS_FUNCTIONOPERATION, "KEY_sys_functionoperation_PRIMARY", SysFunctionoperation.SYS_FUNCTIONOPERATION.ID);
        public static final UniqueKey<SysGroupRecord> KEY_SYS_GROUP_PRIMARY = createUniqueKey(SysGroup.SYS_GROUP, "KEY_sys_group_PRIMARY", SysGroup.SYS_GROUP.ID);
        public static final UniqueKey<SysLogRecord> KEY_SYS_LOG_PRIMARY = createUniqueKey(SysLog.SYS_LOG, "KEY_sys_log_PRIMARY", SysLog.SYS_LOG.ID);
        public static final UniqueKey<SysLoginUserRecord> KEY_SYS_LOGIN_USER_PRIMARY = createUniqueKey(SysLoginUser.SYS_LOGIN_USER, "KEY_sys_login_user_PRIMARY", SysLoginUser.SYS_LOGIN_USER.ID);
        public static final UniqueKey<SysOrgDepartmentPositionRecord> KEY_SYS_ORG_DEPARTMENT_POSITION_PRIMARY = createUniqueKey(SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION, "KEY_sys_org_department_position_PRIMARY", SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.ORGID, SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.POSITIONID, SysOrgDepartmentPosition.SYS_ORG_DEPARTMENT_POSITION.DEPID);
        public static final UniqueKey<SysOrgPositionRecord> KEY_SYS_ORG_POSITION_PRIMARY = createUniqueKey(SysOrgPosition.SYS_ORG_POSITION, "KEY_sys_org_position_PRIMARY", SysOrgPosition.SYS_ORG_POSITION.ORGID, SysOrgPosition.SYS_ORG_POSITION.POSITIONID);
        public static final UniqueKey<SysPermissionFunoperationRecord> KEY_SYS_PERMISSION_FUNOPERATION_PRIMARY = createUniqueKey(SysPermissionFunoperation.SYS_PERMISSION_FUNOPERATION, "KEY_sys_permission_funoperation_PRIMARY", SysPermissionFunoperation.SYS_PERMISSION_FUNOPERATION.FUNID, SysPermissionFunoperation.SYS_PERMISSION_FUNOPERATION.RESOURCESID);
        public static final UniqueKey<SysPositionRecord> KEY_SYS_POSITION_PRIMARY = createUniqueKey(SysPosition.SYS_POSITION, "KEY_sys_position_PRIMARY", SysPosition.SYS_POSITION.ID);
        public static final UniqueKey<SysSubsystemRecord> KEY_SYS_SUBSYSTEM_PRIMARY = createUniqueKey(SysSubsystem.SYS_SUBSYSTEM, "KEY_sys_subsystem_PRIMARY", SysSubsystem.SYS_SUBSYSTEM.ID);
        public static final UniqueKey<SysSubsystemModuleRecord> KEY_SYS_SUBSYSTEM_MODULE_PRIMARY = createUniqueKey(SysSubsystemModule.SYS_SUBSYSTEM_MODULE, "KEY_sys_subsystem_module_PRIMARY", SysSubsystemModule.SYS_SUBSYSTEM_MODULE.ID);
        public static final UniqueKey<SysUsergroupRoleRecord> KEY_SYS_USERGROUP_ROLE_PRIMARY = createUniqueKey(SysUsergroupRole.SYS_USERGROUP_ROLE, "KEY_sys_usergroup_role_PRIMARY", SysUsergroupRole.SYS_USERGROUP_ROLE.ROLEID, SysUsergroupRole.SYS_USERGROUP_ROLE.GROUPID);
        public static final UniqueKey<SysUserGroupRecord> KEY_SYS_USER_GROUP_PRIMARY = createUniqueKey(SysUserGroup.SYS_USER_GROUP, "KEY_sys_user_group_PRIMARY", SysUserGroup.SYS_USER_GROUP.USERID, SysUserGroup.SYS_USER_GROUP.GROUPID);
    }
}
